preprocessing:
  drop_columns : ["id","Unnamed: 32"]
  target : ["diagnosis"]
  axis: 1

model_params:
  test_size: 0.2
  random_state: 42

DataTransform :
  test_size : 0.2
  random_state : 42
  smote_k_neighbours : 5
  n_pca_components: 5