artifacts_root : artifacts


data_ingestion :
  root_dir : artifacts/data_ingestion
  source_url : https://raw.githubusercontent.com/kartheek2003/data_zip_repo/refs/heads/main/data.csv
  local_data_file : artifacts/data_ingestion/data.csv
  
preprocessing:
  df_pre_dir : artifacts/preprocessing


EDA_config:
  report_path : artifacts/report
  df_clean_path : artifacts/preprocessing/df_clean.csv


DataTransform:
  df_path : artifacts/preprocessing/df_clean.csv
  # transformed_df_path : artifacts/DataTransformation
  scaler_path : artifacts/models/scaler
  # pca_model_path : artifacts/models/pca


model_building :
  model_save_path : artifacts/models/
  report_save_path : artifacts/model_report 