artifacts_root : artifacts


data_ingestion :
  root_dir : artifacts/data_ingestion
  source_url : https://raw.githubusercontent.com/kartheek2003/data_zip_repo/refs/heads/main/data.csv
  local_data_file : artifacts/data_ingestion/data.csv
  

EDA_config:
  data_path : artifacts/data_ingestion/data.csv
  report_path : artifacts/data_ingestion/report

